# Generated by Django 5.2.7 on 2026-08-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('filiado_antes_reforma', models.BooleanField(default=False)),
                ('carencia_meses', models.PositiveIntegerField(help_text='Quantidade de contribuições válidas para carência.')),
                ('contribuicao_meses', models.PositiveIntegerField(help_text='Tempo total de contribuição em meses.')),
                ('contribuicao_em_2019_meses', models.PositiveIntegerField(default=0, help_text='Tempo de contribuição apurado em 13/11/2019.')),
                ('salario_medio_atualizado', models.DecimalField(blank=True, decimal_places=2, help_text='Média já atualizada monetariamente pelo CNIS.', max_digits=12, null=True)),
                ('categoria', models.CharField(choices=[('EMPREGADO', 'Empregado, doméstico ou avulso'), ('INDIVIDUAL', 'Contribuinte individual (20%)'), ('SIMPLIFICADO', 'Facultativo / plano simplificado (11%)'), ('MEI', 'MEI / facultativo baixa renda (5%)')], default='EMPREGADO', max_length=15)),
                ('salario_contribuicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resultado', models.JSONField(default=dict, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulacoes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
