# Generated by Django 5.2.7 on 2026-08-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='exposicao_especial_meses',
            field=models.PositiveIntegerField(default=0, help_text='Tempo de efetiva exposição, em meses.'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='grau_exposicao',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(15, '15 anos'), (20, '20 anos'), (25, '25 anos')], null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='ppp_comprovado',
            field=models.BooleanField(default=False, help_text='PPP/LTCAT válido para os períodos especiais.'),
        ),
    ]
