# Generated by Django 5.2.7 on 2026-08-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_simulacao_exposicao_especial_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='atividade_rural_meses',
            field=models.PositiveIntegerField(default=0, help_text='Meses de atividade rural comprovável.'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='comprovacao_rural',
            field=models.BooleanField(default=False, help_text='Documentos/autodeclaração rural disponíveis.'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='tempo_hibrido_meses',
            field=models.PositiveIntegerField(default=0, help_text='Total de meses urbanos e rurais para a modalidade híbrida.'),
        ),
    ]
