# Generated by Django 5.2.7 on 2026-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_simulacao_atividade_rural_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='comprovacao_magisterio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='deficiencia_meses',
            field=models.PositiveIntegerField(default=0, help_text='Tempo de contribuição na condição de pessoa com deficiência.'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='deficiencia_reconhecida',
            field=models.BooleanField(default=False, help_text='Grau reconhecido em avaliação médico-social do INSS.'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='grau_deficiencia',
            field=models.CharField(blank=True, choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave')], max_length=10),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='magisterio_em_2019_meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='magisterio_meses',
            field=models.PositiveIntegerField(default=0, help_text='Tempo exclusivo de magistério na educação básica, em meses.'),
        ),
    ]
